apiVersion: v1
kind: Pod
metadata:
  name: tomcat-nginx
  namespace: dev-ns
  labels:
    app: tomcat
spec:
  containers:
  - name: mytomcat
    image: deepakdev123/tomcat_deploy:5.5.5
  - name: nginx
    image: nginx:1.14.2
